#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs docker run \
  -v "$(pwd):$(pwd)" \
  -w "$(pwd)" \
  --rm \
  secretlint/secretlint secretlint

RET=$?
if [ $RET -eq 0 ] ;then
    exit 0
else
    exit 1
fi
