#!/bin/sh

GITMOJI_CLI=$(which gitmoji)

if [ ! -x "${GITMOJI_CLI}" ]; then
  echo "gitmoji-cli is not installed. Install it if you want template for commit messages."
  exit 0;
fi

readonly COMMIT_MSG_FILE="$1"

cat << __DOC__ >> "${COMMIT_MSG_FILE}"
# gitmoji template to complete
#
__DOC__

${GITMOJI_CLI} --list | sed 's/^/# /' >> "${COMMIT_MSG_FILE}"
